# Generated by Django 3.2.20 on 2023-10-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExerciseName', models.CharField(max_length=50)),
                ('ExerciseType', models.CharField(max_length=50)),
                ('ExerciseDetails', models.CharField(max_length=100)),
                ('ExerciseVideo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=30)),
                ('FoodType', models.CharField(max_length=30)),
                ('Time', models.CharField(max_length=20)),
                ('Quantity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='')),
                ('Description', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=20)),
                ('Title', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Weight', models.CharField(max_length=20)),
                ('Height', models.CharField(max_length=20)),
                ('Place', models.CharField(max_length=20)),
                ('Post', models.CharField(max_length=20)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=20)),
                ('Photo', models.FileField(upload_to='')),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tip', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Weight', models.CharField(max_length=20)),
                ('Height', models.CharField(max_length=20)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('FeedbackUser', models.CharField(max_length=100)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='DietChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chart', models.FileField(upload_to='')),
                ('Description', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.trainer')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=20)),
                ('Reply', models.CharField(max_length=100)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.trainer')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Attendance', models.CharField(max_length=20)),
                ('LOGIN_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('TRAINER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.trainer')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gym_diet_plan_App.user')),
            ],
        ),
    ]
